defmodule WebApplicationWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :web_application

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_web_application_key",
    signing_salt: "QCdJvXbO",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # This can be disabled when using a reverse proxy by setting
  # SERVE_STATIC_ASSETS=false environment variable.
  if Application.compile_env(:web_application, :serve_static_assets, true) do
    plug Plug.Static,
      at: "/",
      from: :web_application,
      gzip: not code_reloading?,
      only: WebApplicationWeb.static_paths()

    # Serve uploaded files from configurable uploads directory
    uploads_path = Application.compile_env(:web_application, :uploads_path, "priv/static/uploads")

    # Only add separate uploads serving if uploads_path is outside priv/static
    unless String.starts_with?(uploads_path, "priv/static") do
      plug Plug.Static,
        at: "/uploads",
        from: uploads_path,
        gzip: false
    end
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :web_application
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug WebApplicationWeb.Router
end
