services:
  db:
    container_name: web_application_db 
    image: postgres:14
    environment:
      POSTGRES_DB: web_application_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: web_application_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    profiles:
      - cache

  opensearch:
    container_name: web_application_opensearch
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch123!
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    profiles:
      - search

  web:
    container_name: web_application_app
    build: .
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    profiles:
      - normal

  web_with_cache:
    container_name: web_application_app_cache
    build: .
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    profiles:
      - cache

  web_with_search:
    container_name: web_application_app_search
    build: .
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - DB_HOST=db
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
    depends_on:
      - db
      - opensearch
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    profiles:
      - search

volumes:
  postgres_data:
  redis_data:
  opensearch_data:

networks:
  default:
    name: web_application_network
