services:
  db:
    container_name: web_application_db 
    image: postgres:14
    environment:
      POSTGRES_DB: web_application_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: web_application_app
    build: .
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/deps
      - /app/_build

volumes:
  postgres_data:

networks:
  default:
    name: web_application_network
